#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Entidades
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.ComponentModel.DataAnnotations;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HealthCare")]
	public partial class BaseDatos : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRol_Info(Rol_Info instance);
    partial void UpdateRol_Info(Rol_Info instance);
    partial void DeleteRol_Info(Rol_Info instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertDireccion(Direccion instance);
    partial void UpdateDireccion(Direccion instance);
    partial void DeleteDireccion(Direccion instance);
    #endregion
		
		public BaseDatos() : 
				base(global::Dominio.Properties.Settings.Default.HealthCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatos(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatos(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatos(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatos(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Rol_Info> Rol_Infos
		{
			get
			{
				return this.GetTable<Rol_Info>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedidos
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Direccion> Direccions
		{
			get
			{
				return this.GetTable<Direccion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol_Info")]
	public partial class Rol_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tipo;
		
		private string _Permisos;
		
		private EntityRef<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnPermisosChanging(string value);
    partial void OnPermisosChanged();
    #endregion
		
		public Rol_Info()
		{
			this._Usuarios = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permisos", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Permisos
		{
			get
			{
				return this._Permisos;
			}
			set
			{
				if ((this._Permisos != value))
				{
					this.OnPermisosChanging(value);
					this.SendPropertyChanging();
					this._Permisos = value;
					this.SendPropertyChanged("Permisos");
					this.OnPermisosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Info_Usuario", Storage="_Usuarios", ThisKey="Id", OtherKey="Rol", IsUnique=true, IsForeignKey=false)]
		public Usuario Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Rol_Info = null;
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Rol_Info = this;
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private string _Telefono;
		
		private int _Dir;
		
		private string _Login;
		
		private string _Password;
		
		private string _Email;
		
		private int _Rol;
		
		private string _imagenTipo;
		
		private byte[] _imagenContenido;
		
		private EntityRef<Pedido> _Pedidos;
		
		private EntitySet<Producto> _Productos;
		
		private EntityRef<Direccion> _Direccions;
		
		private EntityRef<Rol_Info> _Rol_Info;
		
		private EntityRef<Pedido> _Pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDirChanging(int value);
    partial void OnDirChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRolChanging(int value);
    partial void OnRolChanged();
    partial void OnimagenTipoChanging(string value);
    partial void OnimagenTipoChanged();
    partial void OnimagenContenidoChanging(byte[] value);
    partial void OnimagenContenidoChanged();
    #endregion
		
		public Usuario()
		{
			this._Pedidos = default(EntityRef<Pedido>);
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			this._Direccions = default(EntityRef<Direccion>);
			this._Rol_Info = default(EntityRef<Rol_Info>);
			this._Pedido = default(EntityRef<Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
        [Required(ErrorMessage = "Falta el Nombre")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,50}$", ErrorMessage ="No se permiten numeros o caracteres especiales")]
        [StringLength(50)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}

        [RegularExpression(@"^[a-zA-Z''-'\s]{1,150}$", ErrorMessage = "No se permiten numeros o caracteres especiales")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(150)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
        [Required(ErrorMessage = "Falta el Telefono")]
        [RegularExpression(@"^[6,7][0-9]{8}$", ErrorMessage = "El formato del telefono no es correcto")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int NOT NULL")]
		public int Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this.OnDirChanging(value);
					this.SendPropertyChanging();
					this._Dir = value;
					this.SendPropertyChanged("Dir");
					this.OnDirChanged();
				}
			}
		}

        [Required(ErrorMessage = "Indique el login")]
        [RegularExpression(@"^[a-zA-Z0-9''-'\s]{1,20}$", ErrorMessage = "No se permiten caracteres especiales")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "El login es demasiado corto")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}

        [Required(ErrorMessage = "Indique el password")]
        [RegularExpression(@"^[a-zA-Z0-9''-'\s]{1,30}$", ErrorMessage = "No se permiten caracteres especiales")]
        [StringLength(30, MinimumLength = 5, ErrorMessage = "El password es demasiado corto")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}

        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Formato de email invalido")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					if (this._Rol_Info.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagenTipo", DbType="VarChar(50)")]
		public string imagenTipo
		{
			get
			{
				return this._imagenTipo;
			}
			set
			{
				if ((this._imagenTipo != value))
				{
					this.OnimagenTipoChanging(value);
					this.SendPropertyChanging();
					this._imagenTipo = value;
					this.SendPropertyChanged("imagenTipo");
					this.OnimagenTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagenContenido", DbType="Binary(255)", UpdateCheck=UpdateCheck.Never)]
		public byte[] imagenContenido
		{
			get
			{
				return this._imagenContenido;
			}
			set
			{
				if ((this._imagenContenido != value))
				{
					this.OnimagenContenidoChanging(value);
					this.SendPropertyChanging();
					this._imagenContenido = value;
					this.SendPropertyChanged("imagenContenido");
					this.OnimagenContenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Pedido", Storage="_Pedidos", ThisKey="Id", OtherKey="Usuario", IsUnique=true, IsForeignKey=false)]
		public Pedido Pedidos
		{
			get
			{
				return this._Pedidos.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedidos.Entity;
				if (((previousValue != value) 
							|| (this._Pedidos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedidos.Entity = null;
						previousValue.Usuario1 = null;
					}
					this._Pedidos.Entity = value;
					if ((value != null))
					{
						value.Usuario1 = this;
					}
					this.SendPropertyChanged("Pedidos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Producto", Storage="_Productos", ThisKey="Id", OtherKey="Empresa")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Direccion", Storage="_Direccions", ThisKey="Dir", OtherKey="Id", IsUnique=true, IsForeignKey=false)]
		public Direccion Direccions
		{
			get
			{
				return this._Direccions.Entity;
			}
			set
			{
				Direccion previousValue = this._Direccions.Entity;
				if (((previousValue != value) 
							|| (this._Direccions.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Direccions.Entity = null;
						previousValue.Usuario = null;
					}
					this._Direccions.Entity = value;
					if ((value != null))
					{
						value.Usuario = this;
					}
					this.SendPropertyChanged("Direccions");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Info_Usuario", Storage="_Rol_Info", ThisKey="Rol", OtherKey="Id", IsForeignKey=true)]
		public Rol_Info Rol_Info
		{
			get
			{
				return this._Rol_Info.Entity;
			}
			set
			{
				Rol_Info previousValue = this._Rol_Info.Entity;
				if (((previousValue != value) 
							|| (this._Rol_Info.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol_Info.Entity = null;
						previousValue.Usuarios = null;
					}
					this._Rol_Info.Entity = value;
					if ((value != null))
					{
						value.Usuarios = this;
						this._Rol = value.Id;
					}
					else
					{
						this._Rol = default(int);
					}
					this.SendPropertyChanged("Rol_Info");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Usuario", Storage="_Pedido", ThisKey="Id", OtherKey="Empresa", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Usuarios = null;
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Usuarios = this;
						this._Id = value.Empresa;
					}
					else
					{
						this._Id = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Usuario;
		
		private int _Empresa;
		
		private int _Producto;
		
		private int _Estado;
		
		private System.DateTime _Fecha_Insercion;
		
		private System.Nullable<System.DateTime> _Fecha_Entregado;
		
		private int _Cantidad;
		
		private EntityRef<Usuario> _Usuarios;
		
		private EntityRef<Usuario> _Usuario1;
		
		private EntityRef<Producto> _Producto1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsuarioChanging(int value);
    partial void OnUsuarioChanged();
    partial void OnEmpresaChanging(int value);
    partial void OnEmpresaChanged();
    partial void OnProductoChanging(int value);
    partial void OnProductoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnFecha_InsercionChanging(System.DateTime value);
    partial void OnFecha_InsercionChanged();
    partial void OnFecha_EntregadoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_EntregadoChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    #endregion
		
		public Pedido()
		{
			this._Usuarios = default(EntityRef<Usuario>);
			this._Usuario1 = default(EntityRef<Usuario>);
			this._Producto1 = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="Int NOT NULL")]
		public int Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					if (this._Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="Int NOT NULL")]
		public int Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this.OnEmpresaChanging(value);
					this.SendPropertyChanging();
					this._Empresa = value;
					this.SendPropertyChanged("Empresa");
					this.OnEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="Int NOT NULL")]
		public int Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					if (this._Producto1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductoChanging(value);
					this.SendPropertyChanging();
					this._Producto = value;
					this.SendPropertyChanged("Producto");
					this.OnProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Insercion", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Insercion
		{
			get
			{
				return this._Fecha_Insercion;
			}
			set
			{
				if ((this._Fecha_Insercion != value))
				{
					this.OnFecha_InsercionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Insercion = value;
					this.SendPropertyChanged("Fecha_Insercion");
					this.OnFecha_InsercionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Entregado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Entregado
		{
			get
			{
				return this._Fecha_Entregado;
			}
			set
			{
				if ((this._Fecha_Entregado != value))
				{
					this.OnFecha_EntregadoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Entregado = value;
					this.SendPropertyChanged("Fecha_Entregado");
					this.OnFecha_EntregadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Usuario", Storage="_Usuarios", ThisKey="Empresa", OtherKey="Id", IsUnique=true, IsForeignKey=false)]
		public Usuario Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Pedido = null;
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Pedido = this;
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Pedido", Storage="_Usuario1", ThisKey="Usuario", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario1
		{
			get
			{
				return this._Usuario1.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario1.Entity = null;
						previousValue.Pedidos = null;
					}
					this._Usuario1.Entity = value;
					if ((value != null))
					{
						value.Pedidos = this;
						this._Usuario = value.Id;
					}
					else
					{
						this._Usuario = default(int);
					}
					this.SendPropertyChanged("Usuario1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Pedido", Storage="_Producto1", ThisKey="Producto", OtherKey="Id", IsForeignKey=true)]
		public Producto Producto1
		{
			get
			{
				return this._Producto1.Entity;
			}
			set
			{
				Producto previousValue = this._Producto1.Entity;
				if (((previousValue != value) 
							|| (this._Producto1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto1.Entity = null;
						previousValue.Pedidos = null;
					}
					this._Producto1.Entity = value;
					if ((value != null))
					{
						value.Pedidos = this;
						this._Producto = value.Id;
					}
					else
					{
						this._Producto = default(int);
					}
					this.SendPropertyChanged("Producto1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _Categoria;
		
		private decimal _Precio;
		
		private int _Empresa;
		
		private string _imagenTipo;
		
		private byte[] _imagenContenido;
		
		private EntityRef<Pedido> _Pedidos;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnEmpresaChanging(int value);
    partial void OnEmpresaChanged();
    partial void OnimagenTipoChanging(string value);
    partial void OnimagenTipoChanged();
    partial void OnimagenContenidoChanging(byte[] value);
    partial void OnimagenContenidoChanged();
    #endregion
		
		public Producto()
		{
			this._Pedidos = default(EntityRef<Pedido>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}

        [Required(ErrorMessage = "Falta el Nombre")]
        [StringLength(100)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}

        [StringLength(150)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}

        [Required(ErrorMessage = "Falta la categoria")]
        [StringLength(150)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(150)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}

        [Required(ErrorMessage = "Falta el precio")]
        [Range(0.01, 999999999, ErrorMessage = "El precio ha de ser mayor que 0")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="Int NOT NULL")]
		public int Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpresaChanging(value);
					this.SendPropertyChanging();
					this._Empresa = value;
					this.SendPropertyChanged("Empresa");
					this.OnEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagenTipo", DbType="VarChar(50)")]
		public string imagenTipo
		{
			get
			{
				return this._imagenTipo;
			}
			set
			{
				if ((this._imagenTipo != value))
				{
					this.OnimagenTipoChanging(value);
					this.SendPropertyChanging();
					this._imagenTipo = value;
					this.SendPropertyChanged("imagenTipo");
					this.OnimagenTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagenContenido", DbType="Binary(255)", UpdateCheck=UpdateCheck.Never)]
		public byte[] imagenContenido
		{
			get
			{
				return this._imagenContenido;
			}
			set
			{
				if ((this._imagenContenido != value))
				{
					this.OnimagenContenidoChanging(value);
					this.SendPropertyChanging();
					this._imagenContenido = value;
					this.SendPropertyChanged("imagenContenido");
					this.OnimagenContenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Pedido", Storage="_Pedidos", ThisKey="Id", OtherKey="Producto", IsUnique=true, IsForeignKey=false)]
		public Pedido Pedidos
		{
			get
			{
				return this._Pedidos.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedidos.Entity;
				if (((previousValue != value) 
							|| (this._Pedidos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedidos.Entity = null;
						previousValue.Producto1 = null;
					}
					this._Pedidos.Entity = value;
					if ((value != null))
					{
						value.Producto1 = this;
					}
					this.SendPropertyChanged("Pedidos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Producto", Storage="_Usuario", ThisKey="Empresa", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._Empresa = value.Id;
					}
					else
					{
						this._Empresa = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Direccion")]
	public partial class Direccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Calle;
		
		private string _Localidad;
		
		private string _Provincia;
		
		private int _CodigoPostal;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCalleChanging(string value);
    partial void OnCalleChanged();
    partial void OnLocalidadChanging(string value);
    partial void OnLocalidadChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnCodigoPostalChanging(int value);
    partial void OnCodigoPostalChanged();
    #endregion
		
		public Direccion()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}

        [Required(ErrorMessage = "Falta la calle")]
        [StringLength(200)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calle", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Calle
		{
			get
			{
				return this._Calle;
			}
			set
			{
				if ((this._Calle != value))
				{
					this.OnCalleChanging(value);
					this.SendPropertyChanging();
					this._Calle = value;
					this.SendPropertyChanged("Calle");
					this.OnCalleChanged();
				}
			}
		}

        [Required(ErrorMessage = "Falta la localidad")]
        [StringLength(100)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidad", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Localidad
		{
			get
			{
				return this._Localidad;
			}
			set
			{
				if ((this._Localidad != value))
				{
					this.OnLocalidadChanging(value);
					this.SendPropertyChanging();
					this._Localidad = value;
					this.SendPropertyChanged("Localidad");
					this.OnLocalidadChanged();
				}
			}
		}

        [Required(ErrorMessage = "Falta la provincia")]
        [StringLength(100)]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}

        [StringLength(5, ErrorMessage = "El codigo postal debe constar de 5 numeros")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="int NOT NULL")]
		public int CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this.OnCodigoPostalChanging(value);
					this.SendPropertyChanging();
					this._CodigoPostal = value;
					this.SendPropertyChanged("CodigoPostal");
					this.OnCodigoPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Direccion", Storage="_Usuario", ThisKey="Id", OtherKey="Dir", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Direccions = null;
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Direccions = this;
						this._Id = value.Dir;
					}
					else
					{
						this._Id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
